### ISSUE TITLE
exec format error

### ISSUE THREAD

**Issue by MichaelMichaelMichaelMichaelMichael** [paulbouwer/hello-kubernetes#16]
Hi, I've deployed hello-kubernetes to a 4 node raspberry pi k3s cluster and I'm getting the following output:
````
$ kubectl get service hello-kubernetes-custom
NAME                      TYPE           CLUSTER-IP    EXTERNAL-IP   PORT(S)        AGE
hello-kubernetes-custom   LoadBalancer   10.43.27.83   <pending>     80:31288/TCP   13m
$ kubectl get pods
NAME                                       READY   STATUS             RESTARTS   AGE
svclb-hello-kubernetes-custom-snkgf        0/1     Pending            0          13m
svclb-hello-kubernetes-custom-f44xh        0/1     Pending            0          13m
svclb-hello-kubernetes-custom-cghph        0/1     Pending            0          13m
svclb-hello-kubernetes-custom-kfqgg        0/1     Pending            0          13m
hello-kubernetes-custom-6468f86645-x98pq   0/1     CrashLoopBackOff   7          13m
hello-kubernetes-custom-6468f86645-mv2q6   0/1     CrashLoopBackOff   7          13m
hello-kubernetes-custom-6468f86645-gvwcd   0/1     CrashLoopBackOff   7          13m
$ kubectl logs svclb-hello-kubernetes-custom-snkgf
$ kubectl logs hello-kubernetes-custom-6468f86645-x98pq
standard_init_linux.go:211: exec user process caused "exec format error"
````
What could I look at in order to find out what's going wrong?

**Comment by vorburger** [comment]
That's most probably because https://hub.docker.com/r/paulbouwer/hello-kubernetes/tags is for _OS/ARCH_ `linux/amd64` - which your _raspberry pi k3s cluster_ is not... because that's ARM. Hope that makes sense. Have fun & best of luck.

**Comment by MichaelMichaelMichaelMichaelMichael** [comment]
That indeed makes sense, thanks for the explanation!

**Comment by paulbouwer** [comment]
@MichaelMichaelMichaelMichaelMichael stay tuned. I've just started planning a multi-arch version of this image so that you can run it on `linux/amd64`, `linux/arm64`, and `windows/amd64`.

Thanks for bringing this up - using this on a raspberry pi cluster validates my thinking for supporting `arm`.

By the way, what Pi are you running on? Should this be supporting both `linux/arm/v7` and `linux/arm64` ?

**Comment by AkkyOrz** [comment]
@MichaelMichaelMichaelMichaelMichael 

Sorry if this has already been resolved.
I had the same problem and was able to solve it by reading through this issue to find out what caused the problem.

Your problem was caused by the lack of an ARM image on docker hub.
However, if you build the image yourself, you can get it working.
Just clone the repository and build it as described [here](https://github.com/paulbouwer/hello-kubernetes/#build-container-image).
I hope this message will help you.

Thanks to the author of this "hello-kubernetes" repo and the author of the issue!

**Comment by MichaelMichaelMichaelMichaelMichael** [comment]
@paulbouwer 
```
pi@ras0:/home/pi [0] > lsb_release  -a
No LSB modules are available.
Distributor ID:	Debian
Description:	Debian GNU/Linux 10 (buster)
Release:	10
Codename:	buster
pi@ras0:/home/pi [0] > uname -a 
Linux ras0 5.4.51-v8+ #1333 SMP PREEMPT Mon Aug 10 16:58:35 BST 2020 aarch64 GNU/Linux
```
It's a Raspberry Pi 4. Meanwhile, I've added some Intel nuc bricks to that cluster, so for me, the docker buildx is taking the argument linux/x86_64,linux/arm64 in order to match both architectures. After a few weeks of training in kubernetes & docker, I come to the conclusion that having a mixed cluster brings many caveats to take care of when deploying my own apps and makes me learn that topic in depth.

**Comment by rthrprnt** [comment]
I am still experimenting the "exec format error" issue on my mac M1. @paulbouwer have you made the the linux arm 64 version?
